apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-module-23352
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/auth-module-23352
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
